import { Page } from "../../Pages/Page";
const page = new Page()

it('Test, product addition', () => {
    page.navigate()
    page.acceptcookiesbuttonClick()
    page.newArrivalsButtonClick()
    cy.wait(1000)
    page.acmeCupButtonClick()
    page.addToCartButtonClick()
    page.addProductButtonClick()
    page.addProductButtonClick()
    page.addProductButtonClick()
    page.addProductButtonClick()
    cy.wait(2000)
    page.checkTotal125Price()
    page.closeButtonClick()
    page.featuredButtonClick()
    cy.wait(1000)
    page.quarterZipClick()
    page.sizeButtonClick()
    page.addToCartButtonClick()
    cy.wait(2000)
    page.checkTotal215Price()
    page.proceedButtonClick()
    page.enterPhoneNumber()
    page.enterLastName()
    page.enterAddress()
    page.enterCity()
    page.enterPostalCode()
    page.continueButtonClick()
    page.priorityMailInternationalButtonClick()
    page.continueToPaymentButtonClick()
    page.cantAcceptPaymentCheck()
});